version: '3'

services:
  labs:
    hostname: labs
    image: timeloopaccelergy/timeloop-accelergy-pytorch:latest-${DOCKER_ARCH}
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/home/workspace
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - JUPYTER_SWITCHES=--NotebookApp.token=''
