mapping:
  type: fused
  nodes:
    - type: storage
      target: 0
      dspace: [Filter1, Filter2, Fmap1, Fmap3]

    - type: sequential
      branches:
        - - type: storage
            target: 1
            dspace: [Fmap1, Filter1, Fmap2]

          - type: spatial
            rank: P1
            tile_shape: 16

          - type: temporal
            rank: C1
            tile_shape: 1
          - type: temporal
            rank: M1
            tile_shape: 1
          - type: compute
            einsum: Fc1
            target: 2

        - - type: storage
            target: 1
            dspace: [Fmap2, Filter2, Fmap3]

          - type: spatial
            rank: P2
            tile_shape: 16

          - type: temporal
            rank: C2
            tile_shape: 1
          - type: temporal
            rank: M2
            tile_shape: 1
          - type: compute
            einsum: Fc2
            target: 2
